### ISSUE TITLE
XPCSHELL crash

### ISSUE THREAD

**Issue by dmik** [bitwiseworks/mozilla-os2#153]
XPCSHELL is unable to pre-compile resources any more. This is a 38esr regression the needs to be fixed before Beta 6 can be released.

```
Executing D:/Coding/mozilla/master-build-official/dist/bin/xpcshell.exe -g D:/Coding/mozilla/master-build-official/dist/bin/ -a D:/Coding/mozilla/master-build-o
fficial/dist/bin/ -f D:/Coding/mozilla/master/toolkit/mozapps/installer/precompile_cache.js -e precompile_startupcache("resource://gre/");
...
Killed by SIGFPE
pid=0xbc1b ppid=0xbc1a tid=0x0001 slot=0x00bd pri=0x0200 mc=0x0001 ps=0x0010
D:\CODING\MOZILLA\MASTER-BUILD-OFFICIAL\DIST\BIN\XPCSHELL.EXE
XUL 0:0317da0d
cs:eip=005b:12c3da0d      ss:esp=0053:0013d280      ebp=00476c60
 ds=0053      es=0053      fs=150b      gs=0000     efl=00010202
eax=c1e34fd9 ebx=0013d940 ecx=00001370 edx=00000f62 edi=00476c60 esi=0013d940
Process dumping was disabled, use DUMPPROC / PROCDUMP to enable it.
Traceback (most recent call last):
  File "D:/Coding/mozilla/master/toolkit/mozapps/installer/packager.py", line 418, in <module>
    main()
  File "D:/Coding/mozilla/master/toolkit/mozapps/installer/packager.py", line 412, in main
    args.source, gre_path, base)
  File "D:/Coding/mozilla/master/toolkit/mozapps/installer/packager.py", line 171, in precompile_cache
    errors.fatal('Error while running startup cache precompilation')
  File "D:/Coding/mozilla/master/python/mozbuild/mozpack/errors.py", line 101, in fatal
    self._handle(self.FATAL, msg)
  File "D:/Coding/mozilla/master/python/mozbuild/mozpack/errors.py", line 96, in _handle
    raise ErrorMessage(msg)
mozpack.errors.ErrorMessage: Error: Error while running startup cache precompilation
make[3]: *** [stage-package] Error 1
```

**Comment by dryeo** [comment]
On 02/21/16 04:20 AM, Dmitriy Kuminov wrote:
> XPCSHELL is unable to pre-compile resources any more. This is a 38esr
> regression the needs to be fixed before Beta 6 can be released.

While I had the same failure when running make package on Firefox, make 
package succeeds here when packaging SeaMonkey and Thunderbird.

**Comment by dmik** [comment]
Yes, XPCSHELL used to fail here before as well but somehow it didn't trigger the packaging rule to break. Anyway, problem solved.
